apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zvdip6mma-go
  janus-idp.io/tekton: zvdip6mma-go
  backstage.io/kubernetes-id: zvdip6mma-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvdip6mma-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
